title =  "Sunday Afternoon Uplift 007"
description = "<p>Fresh tracks for a new year, with some special attention
paid to Bryan Kearney because I'm really digging his work right now.
Mhammed El Alami is also one of my current faves here.</p>

<ol>
<li>Over The Rings of Saturn (Original Mix) by Dim Line</li>
<li>Lovestruck (Original Mix) by Suncatcher</li>
<li>Wayfarer (David Surok Remix) by Sergey Shabanov</li>
<li>Paradise (Giuseppe Ottaviani Remix) by Sean Mathews</li>
<li>Constellation (Original Mix) by Bernis</li>
<li>Nice Try (Bjorn Akesson Remix) by Tim Lapse</li>
<li>Traveller (Original Mix) by Ikerya Project, Maratone</li>
<li>Te Amo by Bryan Kearney</li>
<li>Spiral 2015 (Original Mix) by Robert Nickson</li></li>
<li>Perfection (Original Mix) by Naoufal Lamrani, Mhammed El Alami</li>
<li>Landscape (Original Mix) by Mehdi Belkadi, Mhammed El Alami</li>
<li>Fields of la Tourette (Ahmed Romel Remix) by New World</li>
<li>Land of Grace (Original Mix) by Manuel Rocca, Mhammed El Alami</li>
<li>To Be Remembered (Original Mix) by Mhammed El Alami</li>
<li>The Things We Should Say (Original Mix) by Bryan Kearney</li>
<li>Flying Blue (Zack Mia Remix) by Ferry Tayle, Daniel Kandi</li>
<li>Broken (New World Remix) by J2p, Jaki Song</li>
<li>Namaste (Skylex Remix) by Obi</li>
<li>Revelation (Extended Mix) by Niko Zografos</li>
<li>Letters To Heaven (Original Mix) by Plutian</li>
<li>Miss You (New World Remix) by Andy Elliass, ARCZI</li>
<li>Ong Namo (Neptune Project's In Search of the Mayan's Remix) by Bryan Kearney & Snatam Kaur</li>
<li>Ethereal Rhapsody (Original Mix) by Simon O'Shine, Sergey Nevone</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-007/"
url = "https://ceejbot.com/sauplift/saup007.html"
date = "January 17 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift007.m4a"
	length = 158500709
	type = "audio/mp4a-latm"
