title =  "Sunday Afternoon Uplift 019"
description = "<p>I've been wanting to feature Solarstone's \"Herald\" in a mix
since in the first moment I heard it, and today I had my chance. This week's
set starts with the Transwave mix of \"Herald\" and goes a little high-energy
for a bit. I'm also a huge fan of Type 41's \"Heiwa\". Bjorn Akesson's \"Language\"
makes another appearance, as one of my favorites of the year.</p>

<ol>
<li>Herald (Transwave Remix) by Solarstone
<li>Take Off (Skylex Remix) by Michael Flint
<li>Diamond by Honan
<li>Solitude by Honan
<li>Equator (Astuni Re-Lift) by Sean Mathews
<li>Catalyst by Type 41
<li>Forceful by Mike Sang
<li>Together Forever by Ignacio Kriman
<li>Heiwa by Type 41
<li>Firefly (Mark W Remix) by Elite Electronic & Three Faces & Amy K
<li>Karanda (Astuni & Manuel Le Saux Remix) by Karanda
<li>Omkara by Manuel Rocca
<li>View Of Kinds (Omniks Remix) by AirLab7
<li>Only for You (Arctic Moon Remix) by Ahmed Romel
<li>Azen (Illitheas Mix) by Mavi & Illitheas
<li>Waiting for You to Come by Ikerya Project
<li>Language by Bjorn Akesson
<li>Insanity by Marco Mc Neil & Alternate High
<li>Rising Sun by Miroslav Vrlik
<li>Ignite (Allen Watts Melodic Remix) by UDM & Allen & Envy
<li>Fahrenheit 451 (Type 41 Remix) by Blanche Noir
<li>Ellie by Rusty Spica
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-019/"
url = "https://ceejbot.com/sauplift/saup019.html"
date = "October 15 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift019.m4a"
	length = 174692915
	type = "audio/mp4a-latm"
