title =  "Sunday Afternoon Uplift 009"
description = "1 Marrakech (Intro Mix) by Simon Bostock
2 Skylight (Original Mix) by Fredrik Miller
3 Yamame (Original Mix) by Hiroki Nagamine pres. Life Stream
4 Weightless (Original Mix) by InnerSync
5 After The Rain (Original Mix) by Mart Sine
6 Fly Away (Extended Mix) by Miroslav Vrlik
7 Apollo 13 (Original Mix) by Nikolauss
8 Blue Sunbeam (Original Mix) by Hiromori Aso
9 Eastern Sea (Liam Wilson Remix) by Solarstone
10 Citadel (Original Mix) by Plutian
11 Secret of the Sahara (Original Mix) by PureNRG
12 Butterfly Effect (Frank Dattilo Remix) by Emanuele Congeddu & 4Seas
13 Never Ending Summer (Original Mix) by Marco Mc Neil
14 The Dragonfly (Original Mix) by Allen & Envy
15 Beautiful (Aly & Fila Remix) by Ferry Corsten
16 Sunflowers Breeze (Original Mix) by Rene Ablaze, Nicola Maddaloni
17 Here & Now (Original Mix) by Sunbrothers, Natalia Meister
18 Golden (Ferry Tayle Remix) by Kyler England, Thomas Hayes
19 Tears of Hope (Original Mix) by Illitheas, Johannes Fischer
20 Chords of Life (Factor B Afterlife Remix) by Reeson
21 Memories (Original Mix) by Afternova
22 Origin (Extended Mix) by Suncatcher
23 Stratosphere by Aura Qualic"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-009/"
date = "April 10 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift009.mp3"
	length = 196173518
	type = "audio/mp3"
