title =  "Sunday Afternoon Uplift 013"
description = "1 Last Goodbye (Etasonic & Marc Tatossian Intro Edit) by George Bakh
2 Midnight Dreams by Martin Libsen
3 Trying to Touch the Horizon (Bluskay & Keyplayer Remix) by Borealnight
4 Million Voices (Extended Mix) by Aly & Fila, Audrey Gallagher, Luke Bond
5 Lost Soul (Daniel Kandi Remix) by Nomosk, Christina Novelli, Roman Messer
6 Adventure (UDM Remix) by Nomosk, Ansia Orchestra
7 Inside The Fire (Mhammed El Alami Dub Mix) by Nomosk, Lucid Blue
8 Echoes (Original Mix) by James Dymond
9 Still feat. Sue McLaren (Jorn van Deynhoven Remix) by Aly & Fila, Sue McLaren
10 Against The Wind (LEV050 Anthem) by Manuel Rocca
11 Skysearch (NoMosk Dub Mix) by Jan Johnston, Feel
12 You & I (Secret Lovers) (Original Mix) by Bluskay
13 Pulser (Mhammed El Alami Remix) by The Cloudy Day
14 Clue Is In The Title (Extended Mix) by Suncatcher
15 North Star (Extended Mix) by Giuseppe Ottaviani, Orkidea
16 From Sunrise To Sunset (Original Mix) by Nomosk, Kiran M Sajeev
17 Take Me With You (Bluskay Remix) by Tenishia, Cathy Burton
18 Sunbeams (Original Mix) by Chronicles, MariaFila
19 Afterlight (Original Mix) by Elite Electronic, Andrey Pashkov
20 Everything feat. Fisher (Aly & Fila Extended Remix) by Vast Vision, Fisher
21 Last Forever (Original Mix) by Illitheas"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-013/"
date = "August 14 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift013.m4a"
	length = 174114162
	type = "audio/mp4a-latm"
