title =  "Sunday Afternoon Uplift 006"
description = "1 Ibiza Bleeps (Original Mix) by Chicane
2 Nubia (Extended Mix) by Aly & Fila, Ferry Tayle
3 All I Need (Suncatcher Remix) by Aurosonic, Katty Heath, Frainbreeze
4 The Things We Should Say (Solarstone Pure Mix) by Bryan Kearney
5 Release Yourself (Original Mix) by Amine Maxwell, Mhammed El Alami
6 Lights feat. Sue McLaren (Giuseppe Ottaviani Remix) by Paul van Dyk, Sue McLaren
7 June (Alex Shevchenko Remix) by Tensile Force
8 Azen (Trance Arts Remix) by Mavi, Illitheas
9 Giver of Life (Original Mix) by New World
10 Vapourize by Aly & Fila & John O'Callaghan
11 Transylvania Cowgirl (Original Mix) by Suncatcher
12 New Life (Fady & Mina Harder Remix) by Danny Claire, Rambacy
13 You May Love (Mhammed El Alami Remix) by Simon O'Shine, Eskova
14 To Be Remembered (Original Mix) by Mhammed El Alami
15 Eonian (Original Mix) by Bernis
16 Paradisum (Original Mix) by Ahmed Romel
17 Daiquiri Sunrise (Original Mix) by Alex Shevchenko
18 Adhara (Original Mix) by Laucco, Danny Legatto
19 Balearic Dream (Plutian Remix) by Marco Mc Neil, Tobias F Weber
20 Spiral 2015 (Original Mix) by Robert Nickson
21 Paradise (Giuseppe Ottaviani Remix) by Sean Mathews
22 Freefall (Original Mix) by Marco Mc Neil
23 Full Throttle (Extended Mix) by Aly & Fila, Sneijder
24 Kinetics (Original Mix) by Fady & Mina
25 Sunbeams (Original Mix) by Chronicles, MariaFila
26 Ethereal Rhapsody (Original Mix) by Simon O'Shine, Sergey Nevone"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-006/"
date = "September 6 2015"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift006.mp3"
	length = 212206578
	type = "audio/mp3"
