title =  "Sunday Afternoon Uplift 001"
description = "Some uplifting & orchestral-breakdown trance for your weekend happiness.

<ol>
<li>Ushio (Emotional Intro Mix) by New World</li>
<li>Amaze by Luke Bond</li>
<li>Nothing to Fear (New World Remix) by Blue Silence & Matt Chowski</li>
<li>Velvet Sun (Aly & Fila Remix) by Majera</li>
<li>Starships Over Alice by Arctic Moon</li>
<li>Only for You (Arctic Moon Remix) by Ahmed Romel</li>
<li>Elate by Andreas Mats</li>
<li>Lenda by SoundLift</li>
<li>Galaxy (Michele Cecchi Remix) by David Surok</li>
<li>Hands of Time by ReOrder & Sue McLaren</li>
<li>Into the Sky by Afternova</li>
<li>Sole Oriente by Vast Vision & Hindsight</li>
<li>Fire Sign (Suncatcher Remix) by Agulo</li>
<li>Mass Effect 2.5 by Thomas Datt</li>
<li>Everlasting (Emotional Mix) by Andy Blueman</li>
<li>Seven Cities (Atlantis Mix) by Solar Stone</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-001/"
url = "https://ceejbot.com/sauplift/saup001.html"
date = "April 12 2015"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift001.mp3"
	length = 158500109
	type = "audio/mp3"
