title =  "Sunday Afternoon Uplift 008"
description = "<p>Welcome to another edition of my Sunday afternoon trance
mix. This week we start mellow with three tracks from Dim Line, then
move into some fresh uplifting trance with a couple of stalwarts thrown
in. This mix stays melodic and cheerful from start to finish.</p>

<li>Fable (Ambient Re-Vision) by Dim Line</li>
<li>Pianeta Terra (Dim Line Remix) by Qpolit</li>
<li>Dual Universe (Blue Twinkle Remix) by Dim Line</li>
<li>7 Suns (Adam Nickey Remix) by Mark Arbor</li>
<li>Ushio by New World</li>
<li>Good Morning (Mhammed El Alami Remix) by Paul Rigel</li>
<li>Renata (Original Mix) by Ralph Friedman</li>
<li>Golden (Ferry Tayle Remix) by Kyler England, Thomas Hayes</li>
<li>Fields of la Tourette (Ahmed Romel Remix) by New World</li>
<li>Tears of Hope (Club Mix) by Illitheas, Johannes Fischer</li>
<li>Sunkissed (Original Mix) by Solis & Sean Truby</li>
<li>Fields of la Tourette (Ahmed Romel Remix) by New World</li>
<li>Freedom (Original Mix) by Aimoon</li>
<li>Nice Try (Bjorn Akesson Remix) by Tim Lapse</li>
<li>Forever Young (Original Mix) by Afternova</li>
<li>Hear Me feat. Jaren (Aly & Fila Remix) by Jaren, Mohamed Ragab</li>
<li>To Be Remembered (Original Mix) by Mhammed El Alami</li>
<li>Cloudless (Marco Mc Neil Remix) by Terry Gaters</li>
<li>Immortal Love (Bernis Remix) by 4 Seas, Giovannie De Sadeleer</li>
<li>Here With You feat. Sarah Shields (Sergey Shabanov Dub Mix) by Max Roelse, Sunbrothers, Sarah Shields</li>
<li>Everything (Original Mix) by Sunbrothers</li>
<li>Between The Stars (Syntouch Remix) by Giovannie De Sadeleer</li>
<li>Rainbow Falls (Original Mix) by Danila Kraev</li>
<li>Miss You (New World Remix) by Andy Elliass, ARCZI"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-008/"
url = "https://ceejbot.com/sauplift/saup008.html"
date = "March 14 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift008.m4a"
	length = 178708665
	type = "audio/mp4a-latm"
