title =  "Sunday Afternoon Uplift 003"
description = "Two hours of recent uplifting trance, mixed for your Sunday afternoon relaxation.

<ol>
<li>Epica (Intro Mix) by Illitheas</li>
<li>Nature Poesia (Emotional Mix) by Time2Rest</li>
<li>Tranquility by Afternova</li>
<li>Liberate by Daniel Kandi & Robert Nickson</li>
<li>The Green March by Karim Raji</li>
<li>Electric Waves (Cold Rush Remix) by Mhammed El Alami, Nathan Brumley</li>
<li>Life Starter by Alex Shevchenko</li>
<li>Beyond The Stars (Emotional Mix) by Kelly Andrew</li>
<li>Anahera (Radio Edit) by Ferry Corsten & Gouryella</li>
<li>Tears for You by Etasonic</li>
<li>Waiting feat. Emma Hewitt (Vocal Mix) by Dash Berlin, Emma Hewitt</li>
<li>Hello Sunrise (Original Mix) by Joer van Ray</li>
<li>Origami (Ferry Tayle Emotional Remix) by Dimension</li>
<li>Aeterna Historia by Sound Apparel</li>
<li>Midnight Dreams (Etasonic Remix) by Martin Libsen</li>
<li>When We Collide (Original Mix) by Simon Bostock, Becca White</li>
<li>Last Goodbye (Etasonic Remix) by George Bakh</li>
<li>Remember This Day by Afternova & Kelly Andrew</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-003/"
url = "https://ceejbot.com/sauplift/saup003.html"
date = "June 28 2015"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift003.mp3"
	length = 163909345
	type = "audio/mpeg"
