title =  "Sunday Afternoon Uplift 009"
description = "<p>My cat helped me perform this mix, by which I mean one of the transitions was hers not mine. See if you can tell which one! I think she doesn't have a career on the decks, though.<p>

<p>Here's another two-hour set of uplifting trance for the next time you need a boost up from the mid-afternoon doldrums.<p>

<ol>
<li>Marrakech (Intro Mix) by Simon Bostock</li>
<li>Skylight (Original Mix) by Fredrik Miller</li>
<li>Yamame (Original Mix) by Hiroki Nagamine pres. Life Stream</li>
<li>Weightless (Original Mix) by InnerSync</li>
<li>After The Rain (Original Mix) by Mart Sine</li>
<li>Fly Away (Extended Mix) by Miroslav Vrlik</li>
<li>Apollo 13 (Original Mix) by Nikolauss</li>
<li>Blue Sunbeam (Original Mix) by Hiromori Aso</li>
<li>Eastern Sea (Liam Wilson Remix) by Solarstone</li>
<li>Citadel (Original Mix) by Plutian</li>
<li>Secret of the Sahara (Original Mix) by PureNRG</li>
<li>Butterfly Effect (Frank Dattilo Remix) by Emanuele Congeddu & 4Seas</li>
<li>Never Ending Summer (Original Mix) by Marco Mc Neil</li>
<li>The Dragonfly (Original Mix) by Allen & Envy</li>
<li>Beautiful (Aly & Fila Remix) by Ferry Corsten</li>
<li>Sunflowers Breeze (Original Mix) by Rene Ablaze, Nicola Maddaloni</li>
<li>Here & Now (Original Mix) by Sunbrothers, Natalia Meister</li>
<li>Golden (Ferry Tayle Remix) by Kyler England, Thomas Hayes</li>
<li>Tears of Hope (Original Mix) by Illitheas, Johannes Fischer</li>
<li>Chords of Life (Factor B Afterlife Remix) by Reeson</li>
<li>Memories (Original Mix) by Afternova</li>
<li>Origin (Extended Mix) by Suncatcher</li>
<li>Stratosphere by Aura Qualic</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-009/"
url = "https://ceejbot.com/sauplift/saup009.html"
date = "April 10 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift009.mp3"
	length = 196173518
	type = "audio/mp3"
