title =  "Sunday Afternoon Uplift 019"
description = "1 Herald (Transwave Remix) by Solarstone
2 Take Off (Skylex Remix) by Michael Flint
3 Diamond by Honan
4 Solitude by Honan
5 Equator (Astuni Re-Lift) by Sean Mathews
6 Catalyst by Type 41
7 Forceful by Mike Sang
8 Together Forever by Ignacio Kriman
9 Heiwa by Type 41
10 Firefly (Mark W Remix) by Elite Electronic & Three Faces & Amy K
11 Karanda (Astuni & Manuel Le Saux Remix) by Karanda
12 Omkara by Manuel Rocca
13 View Of Kinds (Omniks Remix) by AirLab7
14 Only for You (Arctic Moon Remix) by Ahmed Romel
15 Azen (Illitheas Mix) by Mavi & Illitheas
16 Waiting for You to Come by Ikerya Project
17 Language by Bjorn Akesson
18 Insanity by Marco Mc Neil & Alternate High
19 Rising Sun by Miroslav Vrlik
20 Ignite (Allen Watts Melodic Remix) by UDM & Allen & Envy
21 Fahrenheit 451 (Type 41 Remix) by Blanche Noir
22 Ellie by Rusty Spica"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-019/"
date = "October 15 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift019.m4a"
	length = 174692915
	type = "audio/mp4a-latm"
