title =  "Sunday Afternoon Uplift 010"
description = "Ciaran McAuley, Miroslav Vrlik, Illitheas, Type 41, Allen & Envy, Vax, Mhammed el Alami, Manuel Rocca, Suncatcher, and others for you today in a cheerful mix that starts with a little ambience.

<ol>
<li>Maria (Ambient Mix) by Ciaran McAuley</li>
<li>Let There Be Light (Up & Forward Remix) by Vax</li>
<li>Fallen Leaves by Mobil, Mhammed El Alami</li>
<li>The Cry Within (Miroslav Vrlik Remix) by Allen & Envy</li>
<li>Helia feat. Crystal Blakk (Extended Mix) by Jonathan Carvajal, Crystal Blakk, Omar Sherif</li>
<li>Moments Like These by Ciaran McAuley</li>
<li>Isla (Extended Mix) by Ciaran McAuley</li>
<li>Halion by Illitheas</li>
<li>Halcyon (Extended Mix) by Alex van ReeVe</li>
<li>Lionheart by Manuel Rocca</li>
<li>Elysium by Peter Steele</li>
<li>Origin (Extended Mix) by Suncatcher</li>
<li>It Doesn't Rain Forever (Giuseppe Ottaviani Fix) by Ciaran McAuley</li>
<li>Anthea by Ronny K., First Sight</li>
<li>Dreamlands of Kadath (Paul Di White Remix) by Alex Shevchenko</li>
<li>Venezuela (Extended Mix) by Dan Stone</li>
<li>Zephyr by ReOrder</li>
<li>Genesis (Sunbrothers Remix) by Kir Tender</li>
<li>Release Yourself by Amine Maxwell, Mhammed El Alami</li>
<li>Sounds by Danny Claire, Attila Syah</li>
<li>Rising Sun by Miroslav Vrlik</li>
<li>Hope Lies Beyond (Mhammed El Alami Remix) by Type 41</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-010/"
url = "https://ceejbot.com/sauplift/saup010.html"
date = "May 8 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift010.m4a"
	length = 158501009
	type = "audio/mp4a-latm"
