title =  "Sunday Afternoon Uplift 012"
description = "1 Cold Home On Neptune (Original Mix) by Dim Line
2 I'm Coming Home (Mhammed El Alami Dub Mix) by Faith, Ciaran McAuley
3 Philosophy (Original Mix) by Jean Clemence
4 Nocturne (Original Mix) by Plutian
5 Opener (Original Mix) by James Cottle
6 Out There feat. Justine Suissa (Robert Nickson 2016 Extended Remix) by Justine Suissa, Masters & Nickson
7 Last Forever (Original Mix) by Illitheas
8 Okami (Kiran M Sajeev Remix) by Oracle
9 Accelerate (Original Mix) by UDM
10 Aire (Original Mix) by Dreamy, Sam Laxton
11 I'm Sorry (Original Mix) by Type 41, Danny Claire
12 Flicker by Suncatcher
13 Suncatcher by None
14 Midnight Dreams by Martin Libsen
15 Neverending Flight (Bernis Remix) by Syntouch
16 I Will See You Again (Sergey Shabanov Remix) by Anyosel
17 The Bilnk Of Time (Original Mix) by Hiroki Nagamine
18 Whatever (Aly & Fila Extended Remix) by Sassot, Lost Witness
19 Now is Our Time (Original Mix) by Amy Kirkpatrick, Derek Palmer
20 Illuminated (Original Mix) by Michael Retouch
21 Echoes (Original Mix) by James Dymond
22 Forever & Ever (Original Mix) by Hiroki Nagamine
23 Your Distant World (Original Mix) by Simon O´Shine"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-012/"
date = "June 26 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift012.m4a"
	length = 188815392
	type = "audio/mp4a-latm"
