title =  "Sunday Afternoon Uplift 014"
description = "Dreamy yet with a deep groove lurking, that's the theme of this edition of Sunday afternoon uplift. You can, of course, listen on any day of the week. This is the music I prefer to listen to when I'm working or when I need to get deep into a flow state. I hope you find it useful in the same way, or at the very least cheerful and fun to dance to.

<ol>
<li>Resurrection (Original Mix) by Andrew Riqueza</li>
<li>Lifecycle (Peter Hulsmans New Era) by Forerunners</li>
<li>Formless Void (Original Mix) by InnerSync</li>
<li>Empathy (Original Mix) by Dreamy</li>
<li>Northern Stars (Hiroki Nagamine) by Bernis</li>
<li>Diamond (Original Mix) by Honan</li>
<li>No Borders (Original Mix) by Mhammed El Alami, Kheiro & Medi</li>
<li>Mr. Slade (Solarstone Pure Mix) by Gai Barone</li>
<li>Afterlight (Obi Remix) by Elite Electronic, Andrey Pashkov</li>
<li>Scarlett (Original Mix) by PureNRG</li>
<li>Like A Dream (NoMosk Remix) by Ruta, Lucid Blue</li>
<li>Aquis (Original Mix) by Type 41</li>
<li>Light In The Dark (Original Mix) by Marco Mc Neil</li>
<li>Fields of la Tourette by New World</li>
<li>Lugano (Original Mix) by Mhammed El Alami</li>
<li>Different Worlds (Alternate High Emotional Remix) by The Pulsarix, Alternate High</li>
<li>Once Upon a Time (Original Mix) by York, Dreamy</li>
<li>Blissful Blue Sky (Original Mix) by SoundLift</li>
<li>New Horizons (Phil Dinner Remix) by Marcprest</li>
<li>Aaru (Original Mix) by Luke Terry</li>
<li>Valley Of Nature (Aicos Remix) by ToShuk</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-014/"
url = "https://ceejbot.com/sauplift/saup014.html"
date = "August 28 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift014.m4a"
	length = 210146408
	type = "audio/mp4"
