title =  "Sunday Afternoon Uplift 018"
description = "<p>If there's a theme to this week's mix, it's Giuseppe Ottaviani. I work in some older tracks as well as fresh releases to start your week right.</p>

<ol>
<li>One Day (Extended Version) by Giuseppe Ottaviani
<li>Jenova (Illitheas Remix) by Blue Silence
<li>Conrigia by Luuk Goossen & Job Bakker
<li>The Cry Within (Miroslav Vrlik Remix) by Allen & Envy
<li>Under The Sun (Dub Mix) by Mhammed El Alami & Lucid Blue
<li>Captivate (Extended Mix) by Kiran M
<li>Supersonic (Extended Mix) by John Askew
<li>From Desert To Desert by Ikerya Project
<li>Vela by Paul Rigel & Robbie Seed & Omegate
<li>Hysteria (Mhammed El Alami Remix) by Imida
<li>The Pursuit Of Happiness (Extended Mix) by Ciaran McAuley
<li>Eternity by Ula & Mhammed El Alami
<li>Different Worlds by The Pulsarix & Alternate High
<li>Endless Wave (UCast Remix) by Kamaya Painters
<li>Lorelei (Extended Mix) by Plutian
<li>Elation (Extended Mix) by Alan Morris
<li>Fahrenheit 451 (Type 41 Remix) by Blanche Noir
<li>Inscribe (Giuseppe Ottaviani Remix) by APD
<li>Noir (Extended Mix) by A & Z
<li>Proxima (Ikerya Project Remix) by Robert Nickson & Re:Locate
<li>Eerie (Extended Mix) by Fady & Mina
<li>Shortlove (Part Two) (Adam Nickey Remix) by Will Dukster
<li>What Did I Do (Emotional Mix) by Dreamy
<li>The Hunter (Extended Mix) by Sean Mathews
<li>Brightheart (OnAir Mix) by Giuseppe Ottaviani & Christian Burns
<li>Silence (Joseph Alam Remix) by Qpolit
<li>Happiness by David Surok
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-018/"
url = "https://ceejbot.com/sauplift/saup018.html"
date = "October 9 2016"
itunesDuration = 8663

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift018.mp3"
	length = 174692915
	type = "audio/mpeg"
