title =  "Sunday Afternoon Uplift 012"
description = "Today was a hot Pride Sunday, and the mix is sweaty in response. Ends with a Simon O'Shine classic, and travels along the way through some new Illitheas and Hiroki Nagamine.

<ol>
<li>Cold Home On Neptune (Original Mix) by Dim Line</li>
<li>I'm Coming Home (Mhammed El Alami Dub Mix) by Faith, Ciaran McAuley</li>
<li>Philosophy (Original Mix) by Jean Clemence</li>
<li>Nocturne (Original Mix) by Plutian</li>
<li>Opener (Original Mix) by James Cottle</li>
<li>Out There feat. Justine Suissa (Robert Nickson 2016 Extended Remix) by Justine Suissa, Masters & Nickson</li>
<li>Last Forever (Original Mix) by Illitheas</li>
<li>Okami (Kiran M Sajeev Remix) by Oracle</li>
<li>Accelerate (Original Mix) by UDM</li>
<li>Aire (Original Mix) by Dreamy, Sam Laxton</li>
<li>I'm Sorry (Original Mix) by Type 41, Danny Claire</li>
<li>Flicker by Suncatcher</li>
<li>Suncatcher by None</li>
<li>Midnight Dreams by Martin Libsen</li>
<li>Neverending Flight (Bernis Remix) by Syntouch</li>
<li>I Will See You Again (Sergey Shabanov Remix) by Anyosel</li>
<li>The Blink Of Time (Original Mix) by Hiroki Nagamine</li>
<li>Whatever (Aly & Fila Extended Remix) by Sassot, Lost Witness</li>
<li>Now is Our Time (Original Mix) by Amy Kirkpatrick, Derek Palmer</li>
<li>Illuminated (Original Mix) by Michael Retouch</li>
<li>Echoes (Original Mix) by James Dymond</li>
<li>Forever & Ever (Original Mix) by Hiroki Nagamine</li>
<li>Your Distant World (Original Mix) by Simon O´Shine</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-012/"
url = "https://ceejbot.com/sauplift/saup012.html"
date = "June 26 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift012.m4a"
	length = 188815392
	type = "audio/mp4a-latm"
