title =  "Sunday Afternoon Uplift 001"
description = "1 Ushio (Emotional Intro Mix) by New World
2 Amaze by Luke Bond
3 Nothing to Fear (New World Remix) by Blue Silence & Matt Chowski
4 Velvet Sun (Aly & Fila Remix) by Majera
5 Starships Over Alice by Arctic Moon
6 Only for You (Arctic Moon Remix) by Ahmed Romel
7 Elate by Andreas Mats
8 Lenda by SoundLift
9 Galaxy (Michele Cecchi Remix) by David Surok
10 Hands of Time by ReOrder & Sue McLaren
11 Into the Sky by Afternova
12 Sole Oriente by Vast Vision & Hindsight
13 Fire Sign (Suncatcher Remix) by Agulo
14 Mass Effect 2.5 by Thomas Datt
15 Everlasting (Emotional Mix) by Andy Blueman
16 Seven Cities (Atlantis Mix) by Solar Stone"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-001/"
date = "April 12 2015"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift001.mp3"
	length = 158500109
	type = "audio/mp3"
