title =  "Sunday Afternoon Uplift 017"
description = "1 Lotus of The Nile (Sergey Shabanov Chillout Mix) by Sergey Shabanov & Subimpact
2 Lifecycle (Original Mix Remastered) by Forerunners
3 Ethereal Rhapsody by Simon O'Shine & Sergey Nevone
4 Neba by Ferry Corsten & Gouryella
5 Last Forever by Illitheas
6 Once a Lifetime by Dreamy
7 Aquis by Type 41
8 Unforgettable by SoundLift
9 It Doesn't Rain Forever (Giuseppe Ottaviani Fix) by Ciaran McAuley
10 Fields of la Tourette by New World
11 When We Collide by Simon Bostock & Becca White
12 Language by Bjorn Akesson
13 Lenda by SoundLift
14 Born by Alan Morris
15 Titanfall (Extended Mix) by Ferry Tayle & Driftmoon
16 We Were Young feat. Alex & Sierra (Mhammed El Alami Extended Remix) by Gareth Emery & Alex & Sierra
17 Valley Of Nature by ToShuk
18 Macy (Extended Mix) by Dan Stone
19 Skysearch (NoMosk Remix) by Jan Johnston & Feel
20 Take Off (Skylex Remix) by Michael Flint
21 The Heaven's Breath by Etasonic & Laucco
22 Wormhole by Robert Nickson & Dimension"
date = "September 25 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift017.m4a"
	length = 174692915
	type = "audio/mp4a-latm"
