title =  "Sunday Afternoon Uplift 004"
description = "Two hours of fresh uplifting trance for your listening pleasure. Starts in a dark place then moves up and outward to pop-inflected happiness.

<ol>
<li>Fix You vs Zocalo (Chupinolas bootleg) by Armin van Buuren vs Coldplay</li>
<li>The Heroes Theme (Filo & Peri bootleg mix) by Filo & Peri</li>
<li>Anahera (Extended Mix) by Ferry Corsten & Gouryella</li>
<li>Across the Edge (Club Mix) by Thomas Datt</li>
<li>Never Ending Summer (Original Mix) by Marco Mc Neil</li>
<li>Napoleon (Original Mix) by Aly & Fila, Ferry Tayle</li>
<li>Origami (Ferry Tayle Emotional Remix) by Dimension</li>
<li>Arton (Original Mix) by Mhammed El Alami</li>
<li>When We Collide (Original Mix) by Simon Bostock, Becca White</li>
<li>Midnight Dreams (Etasonic Remix) by Martin Libsen</li>
<li>Absolution (Original Mix) by Paul Denton</li>
<li>Air Flow (Emotional Mix) by Playme</li>
<li>Together We Are Strong (2015 Remake) by Afternova</li>
<li>Fields of la Tourette by New World</li>
<li>Wonders of Jakarta by Giovannie De Sadeleer</li>
<li>Outreach by New World</li>
<li>Illuminated (Manuel Rocca Remix) by Michael Retouch</li>
<li>New Rise (Original Mix) by Illitheas, Johannes Fischer, Mhammed El Alami</li>
<li>Release Yourself (Original Mix) by Amine Maxwell, Mhammed El Alami</li>
<li>No One Like You (Original Mix) by Giuseppe Ottaviani</li>
<li>Remember the Youthful Years (Mohamed Ragab Remix) by Suncatcher & Pizz@dox</li>
<li>Electric Waves (Original Mix) by Mhammed El Alami, Nathan Brumley</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-004/"
url = "https://ceejbot.com/sauplift/saup004.html"
date = "August 30 2015"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift004.mp3"
	length = 188005372
	type = "audio/mpeg"
