title =  "Sunday Afternoon Uplift 006"
description = "This one is mostly drawn from new music, with one or two older tracks. Two and half hours this time, because I wanted to make it flow smoothly to that final track. I hope you find it an inspirational and mood-lifting soundtrack for your afternoons, whatever you may be doing.
I perform all my mixes live.

<ol>
1 Ibiza Bleeps (Original Mix) by Chicane
2 Nubia (Extended Mix) by Aly & Fila, Ferry Tayle
3 All I Need (Suncatcher Remix) by Aurosonic, Katty Heath, Frainbreeze
4 The Things We Should Say (Solarstone Pure Mix) by Bryan Kearney
5 Release Yourself (Original Mix) by Amine Maxwell, Mhammed El Alami
6 Lights feat. Sue McLaren (Giuseppe Ottaviani Remix) by Paul van Dyk, Sue McLaren
7 June (Alex Shevchenko Remix) by Tensile Force
8 Azen (Trance Arts Remix) by Mavi, Illitheas
9 Giver of Life (Original Mix) by New World
<li>Vapourize by Aly & Fila & John O'Callaghan</li>
<li>Transylvania Cowgirl (Original Mix) by Suncatcher</li>
<li>New Life (Fady & Mina Harder Remix) by Danny Claire, Rambacy</li>
<li>You May Love (Mhammed El Alami Remix) by Simon O'Shine, Eskova</li>
<li>To Be Remembered (Original Mix) by Mhammed El Alami</li>
<li>Eonian (Original Mix) by Bernis</li>
<li>Paradisum (Original Mix) by Ahmed Romel</li>
<li>Daiquiri Sunrise (Original Mix) by Alex Shevchenko</li>
<li>Adhara (Original Mix) by Laucco, Danny Legatto</li>
<li>Balearic Dream (Plutian Remix) by Marco Mc Neil, Tobias F Weber</li>
<li>Spiral 2015 (Original Mix) by Robert Nickson</li>
<li>Paradise (Giuseppe Ottaviani Remix) by Sean Mathews</li>
<li>Freefall (Original Mix) by Marco Mc Neil</li>
<li>Full Throttle (Extended Mix) by Aly & Fila, Sneijder</li>
<li>Kinetics (Original Mix) by Fady & Mina</li>
<li>Sunbeams (Original Mix) by Chronicles, MariaFila</li>
<li>Ethereal Rhapsody (Original Mix) by Simon O'Shine, Sergey Nevone</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-006/"
url = "https://ceejbot.com/sauplift/saup006.html"
date = "September 6 2015"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift006.mp3"
	length = 212206578
	type = "audio/mp3"
