title =  "Sunday Afternoon Uplift 008"
description = "1 Fable (Ambient Re-Vision) by Dim Line
2 Pianeta Terra (Dim Line Remix) by Qpolit
3 Dual Universe (Blue Twinkle Remix) by Dim Line
4 7 Suns (Adam Nickey Remix) by Mark Arbor
5 Ushio by New World
6 Good Morning (Mhammed El Alami Remix) by Paul Rigel
7 Renata (Original Mix) by Ralph Friedman
8 Golden (Ferry Tayle Remix) by Kyler England, Thomas Hayes
9 Fields of la Tourette (Ahmed Romel Remix) by New World
10 Tears of Hope (Club Mix) by Illitheas, Johannes Fischer
11 Sunkissed (Original Mix) by Solis & Sean Truby
12 Fields of la Tourette (Ahmed Romel Remix) by New World
13 Freedom (Original Mix) by Aimoon
14 Nice Try (Bjorn Akesson Remix) by Tim Lapse
15 Forever Young (Original Mix) by Afternova
16 Hear Me feat. Jaren (Aly & Fila Remix) by Jaren, Mohamed Ragab
17 To Be Remembered (Original Mix) by Mhammed El Alami
18 Cloudless (Marco Mc Neil Remix) by Terry Gaters
19 Immortal Love (Bernis Remix) by 4 Seas, Giovannie De Sadeleer
20 Here With You feat. Sarah Shields (Sergey Shabanov Dub Mix) by Max Roelse, Sunbrothers, Sarah Shields
21 Everything (Original Mix) by Sunbrothers
22 Between The Stars (Syntouch Remix) by Giovannie De Sadeleer
23 Rainbow Falls (Original Mix) by Danila Kraev
24 Miss You (New World Remix) by Andy Elliass, ARCZI"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-008/"
date = "March 14 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift008.m4a"
	length = 178708665
	type = "audio/mp4a-latm"
