title =  "Sunday Afternoon Uplift 007"
description = "1 Over The Rings of Saturn (Original Mix) by Dim Line
2 Lovestruck (Original Mix) by Suncatcher
3 Wayfarer (David Surok Remix) by Sergey Shabanov
4 Paradise (Giuseppe Ottaviani Remix) by Sean Mathews
5 Constellation (Original Mix) by Bernis
6 Nice Try (Bjorn Akesson Remix) by Tim Lapse
7 Traveller (Original Mix) by Ikerya Project, Maratone
8 Te Amo by Bryan Kearney
9 Spiral 2015 (Original Mix) by Robert Nickson
10 Perfection (Original Mix) by Naoufal Lamrani, Mhammed El Alami
11 Landscape (Original Mix) by Mehdi Belkadi, Mhammed El Alami
12 Fields of la Tourette (Ahmed Romel Remix) by New World
13 Land of Grace (Original Mix) by Manuel Rocca, Mhammed El Alami
14 To Be Remembered (Original Mix) by Mhammed El Alami
15 The Things We Should Say (Original Mix) by Bryan Kearney
16 Flying Blue (Zack Mia Remix) by Ferry Tayle, Daniel Kandi
17 Broken (New World Remix) by J2p, Jaki Song
18 Namaste (Skylex Remix) by Obi
19 Revelation (Extended Mix) by Niko Zografos
20 Letters To Heaven (Original Mix) by Plutian
21 Miss You (New World Remix) by Andy Elliass, ARCZI
22 Ong Namo (Neptune Project's In Search of the Mayan's Remix) by Bryan Kearney & Snatam Kaur
23 Ethereal Rhapsody (Original Mix) by Simon O'Shine, Sergey Nevone"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-007/"
date = "January 17 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift007.m4a"
	length = 158500709
	type = "audio/mp4a-latm"
