title =  "Sunday Afternoon Uplift 005"
description = "1 Xperience (Original Mix) by Max Gueli
2 Unpredictable (Afternova Remix Club Edit) by SoundLift
3 Across the Edge (Club Mix) by Thomas Datt
4 Anahera (Extended Mix) by Ferry Corsten & Gouryella
5 Sunlight Touch (Original Mix) by O.B.M Notion, Mhammed El Alami
6 Tengoku (Original Mix) by Hiroki Nagamine, Amber Traill, Spy
7 Napoleon (Original Mix) by Aly & Fila, Ferry Tayle
8 Never Ending Summer (Original Mix) by Marco Mc Neil
9 Valley of The Kings (Sergey Shabanov Remix) by Nikolauss
10 The Orbit (Sky Flight Remix) by Plutian
11 Unforgettable (Original Mix) by SoundLift
12 Daiquiri Sunrise (Original Mix) by Alex Shevchenko
13 Homebound (Original Mix) by Robert Nickson, Re:Locate
14 Fields of la Tourette by New World
15 Hello Sunrise (Plutian Remix) by Joer van Ray
16 All I Need (Suncatcher Remix) by Aurosonic, Katty Heath, Frainbreeze
17 The Things We Should Say (Solarstone Pure Mix) by Bryan Kearney
18 Sapphire Sky (Club Mix) by Illitheas
19 Chrysalis (Original Mix) by Maria Healy
20 Hands of Time by ReOrder & Sue McLaren
21 Paper Dreams (Original Mix) by Bjorn Akesson
22 Into The Sky (2015 Remake) by Afternova"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-005/"
url = "https://ceejbot.com/sauplift/saup005.html"
date = "November 1 2015"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift005.m4a"
	length = 158500509
	type = "audio/mp4a-latm"
