title =  "Sunday Afternoon Uplift 015"
description = "A darker mix this week, to contrast with last week's relentless major-key assault on your bad mood.

<ol>
<li>Rising (Max Gueli Mix) by Sovve</li>
<li>Together (Original Mix) by Russell G</li>
<li>Aaru (UDM Remix) by Luke Terry</li>
<li>Sarah Shields, Drifting (Frainbreeze Remix) by Feel</li>
<li>Hydra, Amber (Extended Mix) by The Thrillseekers</li>
<li>Markus Wilkinson, Open Road (Extended Mix) by Daniel Kandi</li>
<li>Dreamland (Original Mix) by Cold Blue</li>
<li>Curtis Young, Helix (Original Mix) by Bryan Summerville</li>
<li>I Promise (Original Mix) by Plutian</li>
<li>Joel Spencer, When Dreams Become Reality (Extended Mix) by Daniel Kandi</li>
<li>Arhe (Original Mix) by Aleksandar Radicevic</li>
<li>Life Stream, Aerith (Original Mix) by Hiroki Nagamine</li>
<li>Nathia Kate, Moments (Original Mix) by Nomosk</li>
<li>Desert Style (Extended Mix) by Bjorn Akesson</li>
<li>Celestia (Original Mix) by Leroy Moreno</li>
<li>Postive Zero (Suncatcher Remix) by Meridian</li>
<li>Mike Van Fabio, Fable (Mhammed El Alami Remix) by Cherry</li>
<li>Sergey Nevone, Extraterrestrials (Extended Mix) by Simon O'Shine</li>
<li>Driftmoon, Titanfall (Extended Mix) by Ferry Tayle</li>
<li>DJ T.H., Salida Del Sol (Afternova Remix) by Cyre</li>
<li>Touchdown (Original Mix) by Robert Nickson</li>
<li>Blinding Light (Passenger 75 Uplifting Dub) by Mike Shiver</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-015/"
url = "https://ceejbot.com/sauplift/saup015.html"
date = "September 5 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift015.mp3"
	length = 193904814
	type = "audio/mpeg"
