title =  "Sunday Afternoon Uplift 005"
description = "<p>Some fresh tracks and some summer 2015 stalwarts in a 2-hour uplifting mix.
I feel like I should have a 1970s FM station style bumper here:
\"two hours of uninterrupted trance, the way it was meant to be. [laser swoosh]\"
This is exactly the music I want to listen to to get into a tranced-out work state.
I hope you like it too.</p>

<ol>
<li>Xperience (Original Mix) by Max Gueli
<li>Unpredictable (Afternova Remix Club Edit) by SoundLift
<li>Across the Edge (Club Mix) by Thomas Datt
<li>Anahera (Extended Mix) by Ferry Corsten & Gouryella
<li>Sunlight Touch (Original Mix) by O.B.M Notion, Mhammed El Alami
<li>Tengoku (Original Mix) by Hiroki Nagamine, Amber Traill, Spy
<li>Napoleon (Original Mix) by Aly & Fila, Ferry Tayle
<li>Never Ending Summer (Original Mix) by Marco Mc Neil
<li>Valley of The Kings (Sergey Shabanov Remix) by Nikolauss
<li>The Orbit (Sky Flight Remix) by Plutian
<li>Unforgettable (Original Mix) by SoundLift
<li>Daiquiri Sunrise (Original Mix) by Alex Shevchenko
<li>Homebound (Original Mix) by Robert Nickson, Re:Locate
<li>Fields of la Tourette by New World
<li>Hello Sunrise (Plutian Remix) by Joer van Ray
<li>All I Need (Suncatcher Remix) by Aurosonic, Katty Heath, Frainbreeze
<li>The Things We Should Say (Solarstone Pure Mix) by Bryan Kearney
<li>Sapphire Sky (Club Mix) by Illitheas
<li>Chrysalis (Original Mix) by Maria Healy
<li>Hands of Time by ReOrder & Sue McLaren
<li>Paper Dreams (Original Mix) by Bjorn Akesson
<li>Into The Sky (2015 Remake) by Afternova
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-005/"
url = "https://ceejbot.com/sauplift/saup005.html"
date = "November 1 2015"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift005.m4a"
	length = 158500509
	type = "audio/mp4a-latm"
