title =  "Sunday Afternoon Uplift 016"
description = "<p>Some harder club mixes for your afternoon listening, along with a handful of fresh uplifters. This mix was recorded live using Flow 8 Deck.</p>

<ol>
<li>Horizons (Chill Out Mix) by Robert Nickson & Re:Locate</li>
<li>Touch The Sky by Marco Mc Neil</li>
<li>Circle Of Peace (Moonsouls Remix) by Araya & Mark Dreamer</li>
<li>Clue Is In The Title (Extended Mix) by Suncatcher</li>
<li>Peace Sign (Hypaethrame Remix) by Arman Dinarvand & Sepehr Nazari</li>
<li>Eadaoin (U Know) by Ciaran McAuley</li>
<li>Blossoms In The Winter by Hasso Maxime Luft, Lucida</li>
<li>Silence (Marcprest Remix) by Qpolit</li>
<li>Julie (Extended Mix) by Alan Morris</li>
<li>The Promise by Tiff Lacey, Nomosk</li>
<li>Traveller (Astuni Re-Lift) by Ikerya Project, Maratone</li>
<li>Offshore (Akkiles Remix) by Stephane Badey</li>
<li>I Could Be Stronger (But Only For You) (Giuseppe Ottaviani Extended Remix) by Gareth Emery</li>
<li>Eclipse (Club Mix) by MatricK, Ange</li>
<li>The Immortals Behind The Stars (Marco Mc Neil Remix) by Robert Costin</li>
<li>Whisper by Silvernova</li>
<li>Reflections by Luke Bond</li>
<li>Destination (Ikerya Project Remix) by Type 41</li>
<li>Waterland (Skylex Remix) by Braulio Stefield, Solar Traveler</li>
<li>Sky Harbour (Allen Watts Extended Mix) by ReOrder</li>
<li>Stealth Bomber (Chris Schweizer Remix) by Bryan Kearney</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-016/"
url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift019.m4a"
date = "September 18 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift016.m4a"
	length = 174692915
	type = "audio/mp4a-latm"
