title =  "Sunday Afternoon Uplift 004"
description = "1 Fix You vs Zocalo (Chupinolas bootleg) by Armin van Buuren vs Coldplay
2 The Heroes Theme (Filo & Peri bootleg mix) by Filo & Peri
3 Anahera (Extended Mix) by Ferry Corsten & Gouryella
4 Across the Edge (Club Mix) by Thomas Datt
5 Never Ending Summer (Original Mix) by Marco Mc Neil
6 Napoleon (Original Mix) by Aly & Fila, Ferry Tayle
7 Origami (Ferry Tayle Emotional Remix) by Dimension
8 Arton (Original Mix) by Mhammed El Alami
9 When We Collide (Original Mix) by Simon Bostock, Becca White
10 Midnight Dreams (Etasonic Remix) by Martin Libsen
11 Absolution (Original Mix) by Paul Denton
12 Air Flow (Emotional Mix) by Playme
13 Together We Are Strong (2015 Remake) by Afternova
14 Fields of la Tourette by New World
15 Wonders of Jakarta by Giovannie De Sadeleer
16 Outreach by New World
17 Illuminated (Manuel Rocca Remix) by Michael Retouch
18 New Rise (Original Mix) by Illitheas, Johannes Fischer, Mhammed El Alami
19 Release Yourself (Original Mix) by Amine Maxwell, Mhammed El Alami
20 No One Like You (Original Mix) by Giuseppe Ottaviani
21 Remember the Youthful Years (Mohamed Ragab Remix) by Suncatcher & Pizz@dox
22 Electric Waves (Original Mix) by Mhammed El Alami, Nathan Brumley"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-004/"
date = "August 30 2015"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift004.mp3"
	length = 188005372
	type = "audio/mpeg"
