title =  "Sunday Afternoon Uplift 015"
description = "1 Rising (Max Gueli Mix) by Sovve
2 Together (Original Mix) by Russell G
3 Aaru (UDM Remix) by Luke Terry
4 Sarah Shields, Drifting (Frainbreeze Remix) by Feel
5 Hydra, Amber (Extended Mix) by The Thrillseekers
6 Markus Wilkinson, Open Road (Extended Mix) by Daniel Kandi
7 Dreamland (Original Mix) by Cold Blue
8 Curtis Young, Helix (Original Mix) by Bryan Summerville
9 I Promise (Original Mix) by Plutian
10 Joel Spencer, When Dreams Become Reality (Extended Mix) by Daniel Kandi
11 Arhe (Original Mix) by Aleksandar Radicevic
12 Life Stream, Aerith (Original Mix) by Hiroki Nagamine
13 Nathia Kate, Moments (Original Mix) by Nomosk
14 Desert Style (Extended Mix) by Bjorn Akesson
15 Celestia (Original Mix) by Leroy Moreno
16 Postive Zero (Suncatcher Remix) by Meridian
17 Mike Van Fabio, Fable (Mhammed El Alami Remix) by Cherry
18 Sergey Nevone, Extraterrestrials (Extended Mix) by Simon O'Shine
19 Driftmoon, Titanfall (Extended Mix) by Ferry Tayle
20 DJ T.H., Salida Del Sol (Afternova Remix) by Cyre
21 Touchdown (Original Mix) by Robert Nickson
22 Blinding Light (Passenger 75 Uplifting Dub) by Mike Shiver"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-015/"
url = "https://ceejbot.com/sauplift/saup015.html"
date = "September 5 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift015.mp3"
	length = 193904814
	type = "audio/mpeg"
