title =  "Sunday Afternoon Uplift 002"
description = "Emotional, uplifting, and orchestral breakdown trance for putting you in the mood to get your weekend projects done. Mostly recent releases.

<ol>
<li>Nothing to Fear (New World Epic Intro Mix) by Blue Silence & Matt Chowski</li>
<li>Tears for You by Etasonic</li>
<li>See The Sun (Dima Krasnik Dub Mix) by Tom Tyler, ASP Project</li>
<li>Hope Remains (4 Seas & Stacie Remix) by Dominik Walter & Giovannie De Sadeleer</li>
<li>Third Mode Melody (Natlife 5 Late Century Mix) by Natlife feat Thomas Tallis</li>
<li>Hello Sunrise by Joer van Ray</li>
<li>Aeterna Historia by Sound Apparel</li>
<li>Last Goodbye (John Sunlight Remix) by George Bakh</li>
<li>Empathy by Afternova</li>
<li>When We Collide (feat. Becca White) by Simon Bostock</li>
<li>Endless (Intro Mix) by Illitheas</li>
<li>Lenda by SoundLift</li>
<li>Nature Poesia (Emotional Mix) by Time2Rest</li>
<li>Whirling Dervishes by Receptive & New World</li>
<li>The Silver Tree (Original Emotional Mix) by Playme</li>
<li>For Love (Emotional Mix) by Playme</li>
<li>Electric Waves by Mhammed El Alami, Nathan Brumley</li>
<li>Life Starter by Alex Shevchenko</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-002/"
url = "https://ceejbot.com/sauplift/saup002.html"
date = "June 1 2015"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift002.mp3"
	length = 158500209
	type = "audio/mp4a-latm"
