title =  "Sunday Afternoon Uplift 016"
description = "1 Horizons (Chill Out Mix) by Robert Nickson & Re:Locate
2 Touch The Sky by Marco Mc Neil
3 Circle Of Peace (Moonsouls Remix) by Araya & Mark Dreamer
4 Clue Is In The Title (Extended Mix) by Suncatcher
5 Peace Sign (Hypaethrame Remix) by Arman Dinarvand & Sepehr Nazari
6 Eadaoin (U Know) by Ciaran McAuley
7 Blossoms In The Winter by Hasso Maxime Luft, Lucida
8 Silence (Marcprest Remix) by Qpolit
9 Julie (Extended Mix) by Alan Morris
10 The Promise by Tiff Lacey, Nomosk
11 Traveller (Astuni Re-Lift) by Ikerya Project, Maratone
12 Offshore (Akkiles Remix) by Stephane Badey
13 I Could Be Stronger (But Only For You) (Giuseppe Ottaviani Extended Remix) by Gareth Emery
14 Eclipse (Club Mix) by MatricK, Ange
15 The Immortals Behind The Stars (Marco Mc Neil Remix) by Robert Costin
16 Whisper by Silvernova
17 Reflections by Luke Bond
18 Destination (Ikerya Project Remix) by Type 41
19 Waterland (Skylex Remix) by Braulio Stefield, Solar Traveler
20 Sky Harbour (Allen Watts Extended Mix) by ReOrder
21 Stealth Bomber (Chris Schweizer Remix) by Bryan Kearney"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-016/"
date = "September 18 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift016.m4a"
	length = 174692915
	type = "audio/mp4a-latm"
