title =  "Sunday Afternoon Uplift 013"
description = "Nomosk features in this thirteenth edition of uplifting trance for your Sunday afternoon (or your workday), with some highlights from Bluskay.

<ol>
<li>Last Goodbye (Etasonic & Marc Tatossian Intro Edit) by George Bakh</li>
<li>Midnight Dreams by Martin Libsen</li>
<li>Trying to Touch the Horizon (Bluskay & Keyplayer Remix) by Borealnight</li>
<li>Million Voices (Extended Mix) by Aly & Fila, Audrey Gallagher, Luke Bond</li>
<li>Lost Soul (Daniel Kandi Remix) by Nomosk, Christina Novelli, Roman Messer</li>
<li>Adventure (UDM Remix) by Nomosk, Ansia Orchestra</li>
<li>Inside The Fire (Mhammed El Alami Dub Mix) by Nomosk, Lucid Blue</li>
<li>Echoes (Original Mix) by James Dymond</li>
<li>Still feat. Sue McLaren (Jorn van Deynhoven Remix) by Aly & Fila, Sue McLaren</li>
<li>Against The Wind (LEV050 Anthem) by Manuel Rocca</li>
<li>Skysearch (NoMosk Dub Mix) by Jan Johnston, Feel</li>
<li>You & I (Secret Lovers) (Original Mix) by Bluskay</li>
<li>Pulser (Mhammed El Alami Remix) by The Cloudy Day</li>
<li>Clue Is In The Title (Extended Mix) by Suncatcher</li>
<li>North Star (Extended Mix) by Giuseppe Ottaviani, Orkidea</li>
<li>From Sunrise To Sunset (Original Mix) by Nomosk, Kiran M Sajeev</li>
<li>Take Me With You (Bluskay Remix) by Tenishia, Cathy Burton</li>
<li>Sunbeams (Original Mix) by Chronicles, MariaFila</li>
<li>Afterlight (Original Mix) by Elite Electronic, Andrey Pashkov</li>
<li>Everything feat. Fisher (Aly & Fila Extended Remix) by Vast Vision, Fisher</li>
<li>Last Forever (Original Mix) by Illitheas</li>
</ol>"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-013/"
url = "https://ceejbot.com/sauplift/saup013.html"
date = "August 14 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift013.m4a"
	length = 174114162
	type = "audio/mp4a-latm"
