title =  "Sunday Afternoon Uplift 017"
description = "<p>I decided to dig into some of my favorite tracks for this
mix instead of sticking with recent releases.</p>

<ol>
<li>Lotus of The Nile (Sergey Shabanov Chillout Mix) by Sergey Shabanov & Subimpact
<li>Lifecycle (Original Mix Remastered) by Forerunners
<li>Ethereal Rhapsody by Simon O'Shine & Sergey Nevone
<li>Neba by Ferry Corsten & Gouryella
<li>Last Forever by Illitheas
<li>Once a Lifetime by Dreamy
<li>Aquis by Type 41
<li>Unforgettable by SoundLift
<li>It Doesn't Rain Forever (Giuseppe Ottaviani Fix) by Ciaran McAuley
<li>Fields of la Tourette by New World
<li>When We Collide by Simon Bostock & Becca White
<li>Language by Bjorn Akesson
<li>Lenda by SoundLift
<li>Born by Alan Morris
<li>Titanfall (Extended Mix) by Ferry Tayle & Driftmoon
<li>We Were Young feat. Alex & Sierra (Mhammed El Alami Extended Remix) by Gareth Emery & Alex & Sierra
<li>Valley Of Nature by ToShuk
<li>Macy (Extended Mix) by Dan Stone
<li>Skysearch (NoMosk Remix) by Jan Johnston & Feel
<li>Take Off (Skylex Remix) by Michael Flint
<li>The Heaven's Breath by Etasonic & Laucco
<li>Wormhole by Robert Nickson & Dimension
</ol>"
date = "September 25 2016"
itunesDuration = 7105
url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift019.m4a"
mixcloud = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-017/"

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift017.m4a"
	length = 174692915
	type = "audio/mp4a-latm"
