title =  "Sunday Afternoon Uplift 018"
description = "1 One Day (Extended Version) by Giuseppe Ottaviani
2 Jenova (Illitheas Remix) by Blue Silence
3 Conrigia by Luuk Goossen & Job Bakker
4 The Cry Within (Miroslav Vrlik Remix) by Allen & Envy
5 Under The Sun (Dub Mix) by Mhammed El Alami & Lucid Blue
6 Captivate (Extended Mix) by Kiran M
7 Supersonic (Extended Mix) by John Askew
8 From Desert To Desert by Ikerya Project
9 Vela by Paul Rigel & Robbie Seed & Omegate
10 Hysteria (Mhammed El Alami Remix) by Imida
11 The Pursuit Of Happiness (Extended Mix) by Ciaran McAuley
12 Eternity by Ula & Mhammed El Alami
13 Different Worlds by The Pulsarix & Alternate High
14 Endless Wave (UCast Remix) by Kamaya Painters
15 Lorelei (Extended Mix) by Plutian
16 Elation (Extended Mix) by Alan Morris
17 Fahrenheit 451 (Type 41 Remix) by Blanche Noir
18 Inscribe (Giuseppe Ottaviani Remix) by APD
19 Noir (Extended Mix) by A & Z
20 Proxima (Ikerya Project Remix) by Robert Nickson & Re:Locate
21 Eerie (Extended Mix) by Fady & Mina
22 Shortlove (Part Two) (Adam Nickey Remix) by Will Dukster
23 What Did I Do (Emotional Mix) by Dreamy
24 The Hunter (Extended Mix) by Sean Mathews
25 Brightheart (OnAir Mix) by Giuseppe Ottaviani & Christian Burns
26 Silence (Joseph Alam Remix) by Qpolit
27 Happiness by David Surok"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-018/"
date = "October 9 2016"
itunesDuration = 8663

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift018.mp3"
	length = 174692915
	type = "audio/mpeg"
