title =  "Sunday Afternoon Uplift 014"
description = "1 Resurrection (Original Mix) by Andrew Riqueza
2 Lifecycle (Peter Hulsmans New Era) by Forerunners
3 Formless Void (Original Mix) by InnerSync
4 Empathy (Original Mix) by Dreamy
5 Northern Stars (Hiroki Nagamine) by Bernis
6 Diamond (Original Mix) by Honan
7 No Borders (Original Mix) by Mhammed El Alami, Kheiro & Medi
8 Mr. Slade (Solarstone Pure Mix) by Gai Barone
9 Afterlight (Obi Remix) by Elite Electronic, Andrey Pashkov
10 Scarlett (Original Mix) by PureNRG
11 Like A Dream (NoMosk Remix) by Ruta, Lucid Blue
12 Aquis (Original Mix) by Type 41
13 Light In The Dark (Original Mix) by Marco Mc Neil
14 Fields of la Tourette by New World
15 Lugano (Original Mix) by Mhammed El Alami
16 Different Worlds (Alternate High Emotional Remix) by The Pulsarix, Alternate High
17 Once Upon a Time (Original Mix) by York, Dreamy
18 Blissful Blue Sky (Original Mix) by SoundLift
19 New Horizons (Phil Dinner Remix) by Marcprest
20 Aaru (Original Mix) by Luke Terry
21 Valley Of Nature (Aicos Remix) by ToShuk"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-014/"
date = "August 28 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift014.m4a"
	length = 210146408
	type = "audio/mp4"
