title =  "Sunday Afternoon Uplift 011"
description = "1 Cyan (Original Mix) by Dim Line
2 Venezuela (Extended Mix) by Dan Stone
3 Dreamlands of Kadath (Paul Di White Remix) by Alex Shevchenko
4 Aviana (Original Mix) by Cold Rush, Mhammed El Alami
5 Leyenda (Extended Mix) by Andres Sanchez, Michael Kaelios, Spanish Armada
6 After The Rain (Original Mix) by Mart Sine
7 Skydrive (Original Mix) by Second Reason
8 Nocturne (Nick Winth Remix) by Plutian
9 Flashes of the Past (Original Mix) by Cold Rush
10 Lost Hearts (Mark Sherry Remix) by Solarstone
11 Paper Dreams (Original Mix) by Bjorn Akesson
12 Defector (Extended Mix) by James Dymond
13 When Nothing Was Right (Miroslav Vrlik Remix) by Kiyoi, Eky
14 North Star (Factor B Southern Star Remix) by Giuseppe Ottaviani, Orkidea
15 Twin Souls (Extended Mix) by Ferry Tayle
16 ATOM (Original Mix) by Stuart Sleigh
17 Doctor Who (Original Mix) by Giuseppe Ottaviani
18 Halion (Original Mix) by Illitheas
19 Arhe (Bernis Remix) by Aleksandar Radicevic
20 Sunflowers Breeze (Original Mix) by Rene Ablaze, Nicola Maddaloni
21 Virtuous (Original Mix) by Allen & Envy
22 Loyalty (Trance Mix) by Afternova
23 Serbiana Melodica (Original Mix) by Ikerya Project
24 Playa d'en Bossa (Ferry Tayle Remix) by Tarmo Tammel"
url = "https://mixcloud.com/ceejbot/sunday-afternoon-uplift-011/"
date = "June 9 2016"
itunesDuration = 7105

[enclosure]
	url = "http://ceejbot-sauplift.s3-website-us-west-2.amazonaws.com/music/sauplift011.m4a"
	length = 182955216
	type = "audio/mp4a-latm"
